### ISSUE TITLE
trying to setup environment per instructions results in package not found error

### ISSUE THREAD

**Issue by michael-conrad** [mosheman5/DNP#8]
conda env create -f environment.yml 
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - matplotlib-base==3.0.2=py37h167e16e_1001

**Comment by capsudo** [comment]
`matplotlib-base=3.0.2=py37h167e16e_1001` is available on [conda-forge](https://anaconda.org/conda-forge/matplotlib-base/files?version=3.0.2) but for some reason it cannot be found by `conda`, the ones available can be found by doing a `conda search matplotlib-base`, ex `matplotlib-base=3.0.2=py37h167e16e_1002`.

~~After replacing in `matplotlib-base=3.0.2=py37h167e16e_1001` by `matplotlib-base=3.0.2=py37h167e16e_1002` in `environment.yml` it worked.~~ => it did not, incompatibility conflicts

Can't tell you why, I do not know nothing about conda.

edit : turns out `py36h167e16e_1001` is on conda-forge `gcc7` label whereas by default `conda` looks for `main` label. Bad naming IMHO as this thing is certainly not a label. 

**To make it work add line `  - conda-forge/label/gcc7` to `environment.yml` channels.**

**Comment by mosheman5** [comment]
Thanks for your help @didrip , pushed the fix to environment.yml
